// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oohewfdccvygnboyzfxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vaGV3ZmRjY3Z5Z25ib3l6ZnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzk0MjMsImV4cCI6MjA3MTk1NTQyM30.fFPfXzmUZrzKd4GrZdT1lODhfJfdsVm7nxoqSaKNoDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});